routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/posts');

Route::resource('posts', 'PostController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //Non servirebbe avendo usato il nome del model al singolare e la tabella al plurale
    protected $table = 'categories';

    protected $fillable = ['title', 'slug'];

    public function posts()
    {
        return $this->hasMany('App\Post');
    }
    
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //Non servirebbe avendo usato il nome del model al singolare e la tabella al plurale
    protected $table = 'posts';
    
    //Le colonne che vogliamo salvare e editare durante i salvataggi
    protected $fillable = ['category_id', 'title', 'author'];

    //Un post ha una categoria, una categoria avrà diversi post
    public function postInformation()
    {
        return $this->hasOne('App\PostInformation');
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

}

app/PostInformation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PostInformation extends Model
{
    protected $table = 'posts_information';
 
    //Le colonne che vogliamo salvare e editare durante i salvataggi
    protected $fillable = ['post_id', 'description', 'slug'];

    public function post()
    {
        return $this->belongsTo('App\Post');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\Category;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::paginate();

        return view('index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        dd('da creare');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        dd('da creare');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        dd('da creare');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $data = [
            'categories' => Category::all(),
            'post' => $post
        ];

        return view('edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $data = $request->all();

        //aggiorno il post con tutti i data (lui prenderà solo quelli che interessano alla tabella posts, attraverso la variabile fillable che abbiamo messo nel model)
        $post->update($data);

        //Stessa cosa per i postinformation
        $post->postInformation->update($data);

        //ritorniamo alla home
        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //Prima cancello la tabella associata, altrimenti non potrei cancellare post che è la tabella padre
        $post->postInformation->delete();

        $post->delete();

        return redirect()->back();
    }
}

resources/views/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-12">
        <h1>Edit Post: {{ $post->title }}</h1>
    </div>
    <div class="col-12">
        <form action="{{ route('posts.update', $post) }}" method="post">
            @csrf
            @method('patch')

            <div class="form-group">
                <label>Title</label>
                <input value="{{ $post->title }}" class="form-control" name="title" type="text" placeholder="Inserisci un titolo" />
            </div>

            <div class="form-group">
                <label>Autore</label>
                <input value="{{ $post->author }}" class="form-control" name="author" type="text" placeholder="Inserisci un autore" />
            </div>

            <div class="form-group">
                <label>Categoria</label>
                <select class="form-control" name="category_id">
                    <option>---</option>
                    @foreach($categories as $category)

                        <option {{ $post->category->id == $category->id ? 'selected' : '' }} value="{{ $category->id }}">{{ $category->title }}</option>

                    @endforeach
                </select>
            </div>

            <h3>Post Information Data</h3>
            <div class="form-group">
                <label>Descrizione</label>
                <textarea class="form-control" name="description" type="text" placeholder="Inserisci una descrizione">
                    {{ $post->postInformation->description }}
                </textarea>
            </div>
            
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Aggiorna" />
            </div>
        </form>
    </div>

</div>



@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-12">
        <h1>Posts</h1>
    </div>
    <div class="col-12 text-right">
        <a class="btn-primary btn right create" href="{{ route('posts.create') }}">Aggiungi Nuovo</a>
    </div>
    <div class="col-12">
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Category Name</th>
                    <th>Description</th>
                    <th>Aggiorna</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($posts as $post)
                <tr>
                    <td>{{ $post->id }}</td>
                    <td>{{ $post->title }}</td>
                    <td>{{ $post->category->title }}</td>
                    <td>{{ \Illuminate\Support\Str::limit($post->postInformation->description, $limit = 30, $end = '...') }}</td>
                    <td>
                        <a class="btn btn-success" href="{{ route('posts.edit', $post) }}">Aggiorna</a>
                    </td>
                    <td>
                        <form action="{{ route('posts.destroy', $post) }}" method="post">
                            @method('delete')
                            @csrf
                            <input class="btn btn-danger" value="Elimina" type="submit">
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="col-12">
        {{ $posts->links() }}
    </div>
</div>



@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">
    <title>Post</title>
</head>
<body>
    
    <div class="container">
        @yield('content')
    </div>

</body>
</html>